spring.jpa: 
  hibernate: 
    connection: 
      charset: utf8
      useUnicode: true
    ddl-auto: create
  properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

  
server:
  port: 8181
  
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/profile
    username:   
    password: